# -*- coding: utf-8 -*-
"""Project Zero-G.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xp9Kn_4VXxWoHGCaBoAl1nq06zPunoOY
"""

!pip install fastf1 onnx onnxscript

import torch.nn as nn
import onnx
import torch.onnx
import pandas as pd
import torch.optim as optim
import numpy as np
from google.colab import drive
import os
import torch
from sklearn.preprocessing import StandardScaler
import fastf1

drive.mount('/content/drive')
cache_dir = '/content/drive/MyDrive/F1_ZeroG_Data'
os.makedirs(cache_dir, exist_ok=True)
print(f"Directory created at: {cache_dir}")

pip install fastf1

fastf1.Cache.enable_cache('/content/drive/MyDrive/F1_ZeroG_Data')

print("Loading Session Data...")
session = fastf1.get_session(2024, 'Spa', 'Q')
session.load()
ver_lap = session.laps.pick_driver('VER').pick_fastest()
telemetry = ver_lap.get_telemetry()

telemetry.head(10)

car_mass = 798 #upto 900
gravity = 9.81
aero_coef = 0.15
telemetry['Speed_ms'] = telemetry['Speed'] / 3.6
telemetry['Downforce'] = aero_coef * (telemetry['Speed_ms'] ** 2)
telemetry['Normal_Force'] = (car_mass * gravity) + telemetry['Downforce']

telemetry[['Speed', 'Speed_ms', 'Downforce', 'Normal_Force']].describe()

#Coeff of Friction
mu = 1.6
#AntiGravity Factors
antigravity_factor = 0.3

# New Effective Gravity
effective_gravity = gravity * antigravity_factor
telemetry['Effective_Weight'] = car_mass * effective_gravity
telemetry['Normal_Force_LowG'] = telemetry['Effective_Weight'] + telemetry['Downforce']
telemetry['Max_Grip_Newtons'] = telemetry['Normal_Force_LowG'] * mu
telemetry[['Speed', 'Normal_Force', 'Normal_Force_LowG', 'Max_Grip_Newtons']].describe()

simulated_data = []
for g_factor in np.arange(0.0, 1.1, 0.1):
    sim_lap = telemetry[['Speed', 'Speed_ms', 'Downforce']].copy()
    sim_lap['Gravity_Factor'] = np.round(g_factor, 1)
    sim_lap['Effective_Weight'] = car_mass * (gravity * g_factor)
    sim_lap['Normal_Force'] = sim_lap['Effective_Weight'] + sim_lap['Downforce']
    sim_lap['Max_Grip_Newtons'] = sim_lap['Normal_Force'] * mu
    simulated_data.append(sim_lap)
master_dataset = pd.concat(simulated_data, ignore_index=True)
print(f"Original lap data points: {len(telemetry)}")
print(f"Master dataset data points: {len(master_dataset)}")

master_dataset.sample(5)

inputs = master_dataset[['Speed_ms', 'Gravity_Factor']].values
outputs = master_dataset[['Max_Grip_Newtons']].values
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_scaled = scaler_X.fit_transform(inputs)
y_scaled = scaler_y.fit_transform(outputs)
X_tensor = torch.tensor(X_scaled, dtype=torch.float32)
y_tensor = torch.tensor(y_scaled, dtype=torch.float32)
print("Data successfully converted to Tensors!")
print(f"Input Tensor Shape: {X_tensor.shape}")
print(f"Output Tensor Shape: {y_tensor.shape}")

class ZeroG_Surrogate(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
        nn.Linear(in_features=2, out_features=128),
        nn.SiLU(),
        nn.Linear(in_features=128, out_features=128),
        nn.SiLU(),
        nn.Linear(in_features=128, out_features=1))
    def forward(self, x):
        return self.network(x)
model = ZeroG_Surrogate()
print(model)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)
epochs = 500
print("Starting Training.")
for epoch in range(epochs):
    optimizer.zero_grad()
    predictions = model(X_tensor)
    loss = criterion(predictions, y_tensor)
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 50 == 0:
     print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")
print("Training Complete")

dummy_input = torch.tensor([[50.0, 0.5]], dtype=torch.float32)
onnx_file_path = "ZeroG_Physics_Engine.onnx"
torch.onnx.export(model,dummy_input,onnx_file_path,export_params=True,opset_version=18,input_names=['input'],output_names=['output'])
print(f"Success! Model exported to: {onnx_file_path}")

# 1. Load the split/stub model
model_to_fuse = onnx.load("/content/ZeroG_Physics_Engine.onnx")

# 2. Force the model to save everything internally
# By setting 'location' to an empty string and 'all_tensors_to_one_file' to True,
# it forces the weights to stay inside the .onnx protobuf.
onnx.save_model(
    model_to_fuse,
    "ZeroG_Fused_Final.onnx",
    save_as_external_data=False,
    all_tensors_to_one_file=True
)

# 3. Final verification of size
import os
final_size_kb = os.path.getsize("ZeroG_Fused_Final.onnx") / 1024
print(f"Success! New File Size: {final_size_kb:.2f} KB")